dist: trusty
sudo: required
addons:
  apt:
    packages:
    - qemu
    - qemu-user-static
    - binfmt-support
    - parted
    - wget
    - dosfstools
    - zip
script:
  - sudo bash ./create-image
  - zip nw.img.zip nw.img
before_deploy:
  - git config --local user.name "mikevanis"
  - git config --local user.email "hello@mikevanis.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: FAStxOqbH0oCxlbFjfU9wFFCLldmT0KrBoPpfVgSZIhQSnZMs8KfRQuZCfPCxbAEhlnIWdrar/nZNqrT2LoE20xJN6JJxa5jxC2gFHf2c9vnNfaCeNDiZlr2zFT18/OiTPDhzSA0UaxKh+h+TWxi43SqGBmdbrYiSUmcP+csJ5+Cz2Ud2vgnBR4eeh1vGv7Kw5kV5a4S/cazQonuWbLxjAX6Wcpjz1bpFaWlJNsvE5kKATQis0cAQHHB3ITt20uYM9zB1wf9dboOdEhw/G3LFpB2Ka8+osFJPTzGR9vqWcOQUt9FbssDXtZ23J4A0C+yr3aj5geqwSPnPI3OdUUDOHQ1fGyCOxs7+3Ciw8KPqclu5j0JEpQhdCdBVKKrdKanQrhnr/VpvozPiqgqH2+wC8/+J9hovqPYHEmST4nGuB3QNZdJih6tBaZieslcUiA+cLJQQPNt7nSxiTD31xjidiBRCHqVXqpjO99IIPX1ClaZAaRvCdnFJlfuoMCplxTRgCLklRyHYdqosJe7TTkRO+8zAZMKhT/HvpSViSmJ/e+oZ07/o78E/xAvmx27w2h/WCQ/dmU9mzifvJdt1YeH+9oAlSk6MT8OOzXmIgJGz91aWl4LNR4SNOM55Kk4YNHECDS48EV3WQtsc5HZo5mVJJW62U4/reWep9nBSgG7syY=
  file: nw.img.zip
  on:
    repo: mikevanis/travis-raspbian-image
