#!/bin/bash

echo "Hello. This is setup."

# Replace /boot/cmdline.txt since it contains root device mapping to a PARTUUID that
# changed during parted resize. We try to disable the autoresize here as well.
echo "Replace /boot/cmdline.txt"
echo "dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=d5fbc204-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait modules-load=dwc2,g_ether" > "${mount}/boot/cmdline.txt"
cat "${mount}/boot/cmdline.txt"

echo "Enabling OTG"
echo "dtoverlay=dwc2" >> /boot/config.txt

echo "Enabling SSH"
touch /boot/ssh

# Replace /etc/fstab since the non existing PARTUUID has to be changed here as well.
echo "Replace /etc/fstab"
echo "proc            /proc           proc    defaults          0       0" > "${mount}/etc/fstab"
echo "/dev/mmcblk0p1  /boot           vfat    defaults          0       2" >> "${mount}/etc/fstab"
echo "/dev/mmcblk0p2  /               ext4    defaults,noatime  0       1" >> "${mount}/etc/fstab"
cat "${mount}/etc/fstab"

# Give me number of cores avail!
cores=$(nproc)
echo "Number of processor cores: ${cores}"

# Debug disk space.
echo "Checking disk space."
df -h

echo "Setting hostname."
echo "nwcamera" > /etc/hostname
cat /etc/hostname

echo "Enabling camera"
set_config_var start_x 1 /boot/config.txt
CUR_GPU_MEM=$(get_config_var gpu_mem /boot/config.txt)
if [ -z "$CUR_GPU_MEM" ] || [ "$CUR_GPU_MEM" -lt 128 ]; then
  set_config_var gpu_mem 128 /boot/config.txt
fi
sed /boot/config.txt -i -e "s/^startx/#startx/"
sed /boot/config.txt -i -e "s/^fixup_file/#fixup_file/"

echo "Installing packages."
apt-get -y update
apt-get -y install git
