#!/bin/bash

echo "Hello. This is setup."

GPU_MEM=256

# Replace /boot/cmdline.txt since it contains root device mapping to a PARTUUID that
# changed during parted resize. We try to disable the autoresize here as well.
echo "Replace /boot/cmdline.txt"
echo "dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet" > "${mount}/boot/cmdline.txt"
cat "${mount}/boot/cmdline.txt"

# Replace /etc/fstab since the non existing PARTUUID has to be changed here as well.
echo "Replace /etc/fstab"
echo "proc            /proc           proc    defaults          0       0" > "${mount}/etc/fstab"
echo "/dev/mmcblk0p1  /boot           vfat    defaults          0       2" >> "${mount}/etc/fstab"
echo "/dev/mmcblk0p2  /               ext4    defaults,noatime  0       1" >> "${mount}/etc/fstab"
cat "${mount}/etc/fstab"

# Debug disk space.
echo "Checking disk space."
df -h

# Disable automatic filesystem expansion on boot
#rm /usr/lib/raspi-config/init_resize.sh
rm /etc/init.d/resize2fs_once
rm /etc/rc3.d/S01resize2fs_once

echo "Setting hostname."
echo "myraspberrypi" > /etc/hostname
cat /etc/hostname

echo "Enabling SSH."
touch /boot/ssh

echo "Setting gpu_mem."
if grep -q "gpu_mem" /boot/config.txt
then
    sed -i "s/gpu_mem.*/gpu_mem=${GPU_MEM}/" /boot/config.txt
else
    echo "gpu_mem=${GPU_MEM}" >> /boot/config.txt
fi
cat /boot/config.txt | grep "gpu_mem"

# Install Docker
apt-get update
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common

curl -fsSL https://download.docker.com/linux/raspbian/gpg | apt-key add -
echo "deb [arch=armhf] https://download.docker.com/linux/raspbian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
apt-get update

apt-cache madison docker-ce
apt-get install -y docker-ce=18.06.1~ce~3-0~raspbian
sudo usermod -aG docker pi

# Test Docker
docker run hypriot/armhf-hello-world

echo "Congratulations! Docker installed successfully."
